import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('employees_1000.csv')
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.columns)
print(df.groupby('department')['salary'].mean())
print(df.groupby('department')['salary'].sum())
print(df.groupby('department')['salary'].max())
print(df.groupby('department')['salary'].min())
print(df.groupby('department')['salary'].std())
print(df.groupby('department')['salary'].count())
print(df.sort_values(by='salary', ascending=False).head(10))
plt.hist(df['salary'], bins=20)
plt.xlabel('Salary')
plt.ylabel('Frequency')
plt.title('Distribution of Salaries')
plt.show()
plt.scatter(df['age'], df['salary'])
plt.xlabel('Age')   
plt.ylabel('Salary')
plt.title('Age vs. Salary')
plt.show()
plt.plot(df.groupby('department')['salary'].mean())
plt.xlabel('Department')    
plt.ylabel('Average Salary')
plt.title('Average Salary by Department')
plt.xticks(rotation=45)
plt.show()